using System.Collections;
using System.Reflection;
using Client.View.UiControl;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using UnityEngine.UI;

namespace Client.Tests.PlayMode
{
  // Mostly generated by AI
  public class HintHighlightPlayModeTests
  {
    [UnityTest]
    public IEnumerator HideHint_DisablesImage()
    {
      var host = new GameObject("HintHost");
      host.SetActive(false);
      var hint = host.AddComponent<HintHighlight>();
      var img = host.AddComponent<Image>();
      img.enabled = true;

      SetPrivateField(hint, "_highlightImg", img);
      SetPrivateField(hint, "_highlightAfterMs", 1);
      SetPrivateField(hint, "_scaleDurationSec", 0.01f);

      host.SetActive(true);
      yield return null;

      hint.HideHint();

      Assert.That(img.enabled, Is.False);

      Object.Destroy(host);
    }

    [UnityTest]
    public IEnumerator ShowHintDelayed_EnablesImageAfterConfiguredDelay()
    {
      var host = new GameObject("HintHost");
      host.SetActive(false);
      var hint = host.AddComponent<HintHighlight>();
      var img = host.AddComponent<Image>();

      SetPrivateField(hint, "_highlightImg", img);
      SetPrivateField(hint, "_highlightAfterMs", 10);
      SetPrivateField(hint, "_scaleDurationSec", 0.01f);

      host.SetActive(true);
      yield return null; // Awake: HideHint + ShowHintDelayed

      img.enabled = false;
      hint.HideHint();
      hint.ShowHintDelayed();

      Assert.That(img.enabled, Is.False);

      yield return new WaitForSeconds(0.03f);

      Assert.That(img.enabled, Is.True);

      Object.Destroy(host);
    }

    private static void SetPrivateField(object target, string fieldName, object value)
    {
      var field = target.GetType().GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);
      Assert.That(field, Is.Not.Null, $"Field '{fieldName}' was not found on type {target.GetType().Name}");
      field!.SetValue(target, value);
    }
  }
}
