using System.Collections;
using System.Reflection;
using Client.View.MatchEndAnimation;
using Client.View.UiControl;
using NUnit.Framework;
using TMPro;
using UnityEngine;
using UnityEngine.TestTools;
using UnityEngine.UI;

namespace Client.Tests.PlayMode
{
  // Mostly generated by AI
  public class MatchEndAnimatorPlayModeTests
  {
    [UnityTest]
    public IEnumerator Animate_SetsUiStateAndDisablesHintObject()
    {
      var host = new GameObject("MatchEndAnimatorHost");
      host.SetActive(false);
      var animator = host.AddComponent<MatchEndAnimator>();

      var root = new GameObject("Root");
      root.SetActive(false);

      var textObj = new GameObject("Text");
      var text = textObj.AddComponent<TextMeshProUGUI>();

      var canvasGroupObj = new GameObject("CanvasGroup");
      var canvasGroup = canvasGroupObj.AddComponent<CanvasGroup>();
      canvasGroup.alpha = 1.0f;

      var hintObj = new GameObject("Hint");
      hintObj.SetActive(false);
      var hintImage = hintObj.AddComponent<Image>();
      var hint = hintObj.AddComponent<HintHighlight>();
      SetPrivateField(hint, "_highlightImg", hintImage);
      hintObj.SetActive(true);

      var config = ScriptableObject.CreateInstance<AnimationConfig>();
      SetPrivateField(config, "_matchEndRevealSec", 0.01f);

      SetPrivateField(animator, "_root", root);
      SetPrivateField(animator, "_text", text);
      SetPrivateField(animator, "_canvasGroup", canvasGroup);
      SetPrivateField(animator, "_animationConfig", config);
      SetPrivateField(animator, "_hintHighlight", hint);

      host.SetActive(true);
      yield return null;

      animator.Animate(MatchEndKind.Lose);

      Assert.That(root.activeSelf, Is.True);
      Assert.That(text.text, Is.EqualTo("LOSE"));
      Assert.That(hint.gameObject.activeSelf, Is.False);
      Assert.That(canvasGroup.alpha, Is.EqualTo(0.0f).Within(0.0001f));

      Object.Destroy(host);
      Object.Destroy(root);
      Object.Destroy(textObj);
      Object.Destroy(canvasGroupObj);
      Object.Destroy(hintObj);
      Object.Destroy(config);
    }

    private static void SetPrivateField(object target, string fieldName, object value)
    {
      var field = target.GetType().GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);
      Assert.That(field, Is.Not.Null, $"Field '{fieldName}' was not found on type {target.GetType().Name}");
      field!.SetValue(target, value);
    }
  }
}
