using System.Collections;
using System.Reflection;
using Client.View.Notification;
using NUnit.Framework;
using TMPro;
using UnityEngine;
using UnityEngine.TestTools;

namespace Client.Tests.PlayMode
{
  // Mostly generated by AI
  public class NotificationManagerPlayModeTests
  {
    [UnityTest]
    public IEnumerator Show_InitializesTextAndActivatesTransformObject()
    {
      var host = new GameObject("NotificationHost");
      host.SetActive(false);
      var manager = host.AddComponent<NotificationManager>();

      var transObj = new GameObject("NotificationRect");
      transObj.SetActive(true);
      var trans = transObj.AddComponent<RectTransform>();

      var textObj = new GameObject("NotificationText");
      var text = textObj.AddComponent<TextMeshProUGUI>();

      var initialPos = new Vector3(12f, 34f, 0f);
      var finalPos = new Vector3(45f, 56f, 0f);
      var color = new Color(0.2f, 0.7f, 1f, 1f);

      SetPrivateField(manager, "_text", text);
      SetPrivateField(manager, "_trans", trans);
      SetPrivateField(manager, "_initialPos", initialPos);
      SetPrivateField(manager, "_finalPos", finalPos);
      SetPrivateField(manager, "_transparencyChangeSec", 0.01f);
      SetPrivateField(manager, "_transitionSec", 0.01f);
      SetPrivateField(manager, "_notificationColor", color);

      host.SetActive(true);
      yield return null;

      manager.Show("NetworkError");

      Assert.That(text.text, Is.EqualTo("NetworkError"));
      Assert.That(trans.gameObject.activeSelf, Is.True);
      Assert.That(trans.anchoredPosition, Is.EqualTo((Vector2)initialPos));
      Assert.That(text.color, Is.EqualTo(Color.clear));

      Object.Destroy(host);
      Object.Destroy(transObj);
      Object.Destroy(textObj);
    }

    [UnityTest]
    public IEnumerator Show_WhenCalledTwice_SecondCallOverridesState()
    {
      var host = new GameObject("NotificationHost");
      host.SetActive(false);
      var manager = host.AddComponent<NotificationManager>();

      var transObj = new GameObject("NotificationRect");
      transObj.SetActive(true);
      var trans = transObj.AddComponent<RectTransform>();

      var textObj = new GameObject("NotificationText");
      var text = textObj.AddComponent<TextMeshProUGUI>();

      var initialPos = new Vector3(5f, 7f, 0f);
      var finalPos = new Vector3(100f, 120f, 0f);
      var color = new Color(0.8f, 0.3f, 0.2f, 1f);

      SetPrivateField(manager, "_text", text);
      SetPrivateField(manager, "_trans", trans);
      SetPrivateField(manager, "_initialPos", initialPos);
      SetPrivateField(manager, "_finalPos", finalPos);
      SetPrivateField(manager, "_transparencyChangeSec", 0.2f);
      SetPrivateField(manager, "_transitionSec", 0.2f);
      SetPrivateField(manager, "_notificationColor", color);

      host.SetActive(true);
      yield return null;

      manager.Show("First");
      yield return null; // let first animation start
      manager.Show("Second");

      Assert.That(text.text, Is.EqualTo("Second"));
      Assert.That(trans.gameObject.activeSelf, Is.True);
      Assert.That(trans.anchoredPosition, Is.EqualTo((Vector2)initialPos));
      Assert.That(text.color, Is.EqualTo(Color.clear));

      Object.Destroy(host);
      Object.Destroy(transObj);
      Object.Destroy(textObj);
    }

    private static void SetPrivateField(object target, string fieldName, object value)
    {
      var field = target.GetType().GetField(fieldName, BindingFlags.Instance | BindingFlags.NonPublic);
      Assert.That(field, Is.Not.Null, $"Field '{fieldName}' was not found on type {target.GetType().Name}");
      field!.SetValue(target, value);
    }
  }
}
