using Client.View.UiControl;
using UnityEditor;
using UnityEditor.UI;

namespace Client.View
{
  // Class mostly generated by AI
  [CustomEditor(typeof(MultiTargetButton), true)]
  [CanEditMultipleObjects]
  public class MultiTargetButtonEditor : ButtonEditor
  {
    private SerializedProperty _extraTargetsProp;

    protected override void OnEnable()
    {
      base.OnEnable();
      _extraTargetsProp = serializedObject.FindProperty("_extraTargets");
    }

    public override void OnInspectorGUI()
    {
      base.OnInspectorGUI();

      serializedObject.Update();
      EditorGUILayout.PropertyField(_extraTargetsProp, true);
      serializedObject.ApplyModifiedProperties();
    }
  }
}