// This class mostly generated by AI

using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using Server.ServerModel.Data;
using Server.ServerModel.Logic;
using Shared.SharedModel.Data;

namespace Server.ServerModelTests
{
  public class MatchLogicTests
  {
    [Test]
    public void GenerateMatchData_DealsFullDeckEvenly()
    {
      var matchData = new MatchInitializer().GenerateMatchData();

      Assert.That(matchData.Players.Length, Is.EqualTo(2));

      var allCards = new List<CardData>(52);
      foreach (var player in matchData.Players)
      {
        Assert.That(player.PlayDeck.Count, Is.EqualTo(26));
        Assert.That(player.SidePile.Count, Is.EqualTo(0));

        while (player.PlayDeck.Count > 0)
          allCards.Add(player.PlayDeck.Pop());
      }

      Assert.That(allCards.Count, Is.EqualTo(52));

      var unique = new HashSet<(CardRank Rank, CardSuit Suit)>();
      foreach (var card in allCards)
        unique.Add((card.Rank, card.Suit));

      Assert.That(unique.Count, Is.EqualTo(52));
    }

    [Test]
    public void GenerateMatchData_HasExactRankSuitDistribution()
    {
      var matchData = new MatchInitializer().GenerateMatchData();
      var rankCounts = new Dictionary<CardRank, int>();
      var suitCounts = new Dictionary<CardSuit, int>();

      foreach (var player in matchData.Players)
      {
        while (player.PlayDeck.Count > 0)
        {
          var card = player.PlayDeck.Pop();
          rankCounts[card.Rank] = rankCounts.TryGetValue(card.Rank, out var rankCount) ? rankCount + 1 : 1;
          suitCounts[card.Suit] = suitCounts.TryGetValue(card.Suit, out var suitCount) ? suitCount + 1 : 1;
        }
      }

      foreach (CardRank rank in System.Enum.GetValues(typeof(CardRank)))
        Assert.That(rankCounts[rank], Is.EqualTo(4));

      foreach (CardSuit suit in System.Enum.GetValues(typeof(CardSuit)))
        Assert.That(suitCounts[suit], Is.EqualTo(13));
    }

    [Test]
    public void ProcessTurn_WhenHigherCard_WinnerTakesBoth()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      // Top cards are the last pushed cards.
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Clubs));

      var response = processor.ProcessTurn(matchData);

      Assert.That(matchData.Players[0].SidePile.Count, Is.EqualTo(2));
      Assert.That(matchData.Players[1].SidePile.Count, Is.EqualTo(0));
      Assert.That(matchData.Players[0].RevealedOnTable, Is.Null);
      Assert.That(matchData.Players[1].RevealedOnTable, Is.Null);
      Assert.That(response.MatchResult, Is.Not.Null);
      Assert.That(response.MatchResult.WinnerPlayerIdx, Is.EqualTo(0));
    }

    [Test]
    public void ProcessTurn_WhenMatchAlreadyFinished_DoesNothing()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();
      matchData.EndMatch(0);

      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Hearts));

      var beforeTotal = CountAllCards(matchData);
      var response = processor.ProcessTurn(matchData);
      var afterTotal = CountAllCards(matchData);

      Assert.That(response.TurnEvents.Count, Is.EqualTo(0));
      Assert.That(beforeTotal, Is.EqualTo(afterTotal));
      Assert.That(matchData.Result.WinnerPlayerIdx, Is.EqualTo(0));
    }

    [Test]
    public void ProcessTurn_WhenWarOccurs_WinnerTakesAllWarCards()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      // Player 0: reveal K, 3 hidden, then reveal A.
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Three, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Four, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Spades));

      // Player 1: reveal K, 3 hidden, then reveal Q.
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Queen, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Three, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Four, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Hearts));

      var response = processor.ProcessTurn(matchData);

      Assert.That(matchData.Players[0].SidePile.Count, Is.EqualTo(10));
      Assert.That(matchData.Players[1].SidePile.Count, Is.EqualTo(0));
      Assert.That(matchData.Players[0].HiddenOnTable.Count, Is.EqualTo(0));
      Assert.That(matchData.Players[1].HiddenOnTable.Count, Is.EqualTo(0));
      Assert.That(matchData.Players[0].RevealedOnTable, Is.Null);
      Assert.That(matchData.Players[1].RevealedOnTable, Is.Null);
      Assert.That(response.TurnEvents, Is.Not.Empty);
    }

    [Test]
    public void ProcessTurn_WhenWarAndPlayerCannotProvide3FaceDown_Loses()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      // Tie on first reveal.
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Three, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Four, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Five, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Six, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Spades));
      
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Three, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Hearts));

      var response = processor.ProcessTurn(matchData);

      Assert.That(response.MatchResult, Is.Not.Null);
      Assert.That(response.MatchResult.WinnerPlayerIdx, Is.EqualTo(0));
    }

    [Test]
    public void ProcessTurn_WhenWarAndBothCannotContinue_SetsDraw()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Spades));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Hearts));

      var response = processor.ProcessTurn(matchData);

      Assert.That(response.MatchResult, Is.Not.Null);
      Assert.That(response.MatchResult.WinnerPlayerIdx, Is.Null);
    }

    [Test]
    public void ProcessTurn_WhenMultipleConsecutiveWars_ResolvesCorrectly()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      // P0: K (reveal), 3 hidden, Q (reveal), 3 hidden, A (reveal)
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Three, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Four, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Queen, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Five, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Six, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Seven, CardSuit.Spades));
      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Spades));

      // P1: K (reveal), 3 hidden, Q (reveal), 3 hidden, J (reveal)
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Jack, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Three, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Four, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Queen, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Five, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Six, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Seven, CardSuit.Hearts));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.King, CardSuit.Hearts));

      processor.ProcessTurn(matchData);

      Assert.That(matchData.Players[0].SidePile.Count, Is.EqualTo(18));
      Assert.That(matchData.Players[1].SidePile.Count, Is.EqualTo(0));
    }

    [Test]
    public void ProcessTurn_ClearsTableCardsAfterTakingPile()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Clubs));

      processor.ProcessTurn(matchData);

      Assert.That(matchData.Players[0].HiddenOnTable.Count, Is.EqualTo(0));
      Assert.That(matchData.Players[1].HiddenOnTable.Count, Is.EqualTo(0));
      Assert.That(matchData.Players[0].RevealedOnTable, Is.Null);
      Assert.That(matchData.Players[1].RevealedOnTable, Is.Null);
    }

    [Test]
    public void ProcessTurn_EmitsExpectedEventSequence_ForSimpleTurn()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      matchData.Players[0].PlayDeck.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Clubs));

      var response = processor.ProcessTurn(matchData);
      var kinds = response.TurnEvents.Select(x => x.EventKind).ToArray();

      Assert.That(kinds.Length, Is.EqualTo(3));
      Assert.That(kinds[0], Is.EqualTo(TurnEventKind.RevealTopFromDeck));
      Assert.That(kinds[1], Is.EqualTo(TurnEventKind.RevealTopFromDeck));
      Assert.That(kinds[2], Is.EqualTo(TurnEventKind.PutToSidePile));
    }

    [Test]
    public void ProcessTurn_WhenDeckEmptyAndSidePileHasCards_UsesSidePileAsDeck()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      matchData.Players[0].SidePile.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Clubs));

      var response = processor.ProcessTurn(matchData);

      Assert.That(ContainsEvent(response.TurnEvents, TurnEventKind.UseSidePileAsDeck), Is.True);
      Assert.That(matchData.Players[0].SidePile.Count, Is.EqualTo(2));
    }

    [Test]
    public void UseSidePileAsDeck_TransfersCardsAndAllowsTurnProgress()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      matchData.Players[0].SidePile.Push(new CardData(CardRank.King, CardSuit.Spades));
      matchData.Players[0].SidePile.Push(new CardData(CardRank.Ace, CardSuit.Spades));
      matchData.Players[0].SidePile.Push(new CardData(CardRank.Queen, CardSuit.Spades));
      matchData.Players[1].PlayDeck.Push(new CardData(CardRank.Two, CardSuit.Clubs));

      var response = processor.ProcessTurn(matchData);

      Assert.That(ContainsEvent(response.TurnEvents, TurnEventKind.UseSidePileAsDeck), Is.True);
      Assert.That(matchData.Players[0].PlayDeck.Count, Is.GreaterThanOrEqualTo(0));
      Assert.That(matchData.Players[0].SidePile.Count, Is.GreaterThanOrEqualTo(0));
      Assert.That(CountAllCards(matchData), Is.EqualTo(4));
    }

    [Test]
    public void ProcessTurn_WhenBothPlayersHaveNoCards_EndsWithDraw()
    {
      var matchData = new ServerMatchData();
      var processor = new MatchProcessor();

      var response = processor.ProcessTurn(matchData);

      Assert.That(response.MatchResult, Is.Not.Null);
      Assert.That(response.MatchResult.WinnerPlayerIdx, Is.Null);
    }

    [Test]
    public void CardsDeck_PopOnEmpty_Throws()
    {
      var deck = new CardsDeck();
      Assert.Throws<System.ArgumentOutOfRangeException>(() => deck.Pop());
    }

    [Test]
    public void ProcessTurn_NeverChangesTotalCardCount()
    {
      var matchData = new MatchInitializer().GenerateMatchData();
      var processor = new MatchProcessor();
      var initialCount = CountAllCards(matchData);

      for (var i = 0; i < 30 && matchData.Result == null; i++)
      {
        processor.ProcessTurn(matchData);
        Assert.That(CountAllCards(matchData), Is.EqualTo(initialCount));
      }
    }

    private static bool ContainsEvent(IEnumerable<Shared.SharedModel.Dto.TurnEventData> events, TurnEventKind kind)
    {
      foreach (var turnEvent in events)
        if (turnEvent.EventKind == kind)
          return true;

      return false;
    }

    private static int CountAllCards(ServerMatchData matchData)
    {
      var count = 0;
      foreach (var player in matchData.Players)
      {
        count += player.PlayDeck.Count;
        count += player.SidePile.Count;
        count += player.HiddenOnTable.Count;
        if (player.RevealedOnTable != null)
          count += 1;
      }

      return count;
    }
  }
}
