using System.Collections.Generic;
using Client.Model;
using NUnit.Framework;
using Shared.SharedModel.Data;

namespace Client.Tests.EditorMode
{
  // Mostly generated by AI
  public class AppModelTests
  {
    [Test]
    public void UpdatePlayers_UsesLastEventPerPlayer()
    {
      var model = new AppModel();
      model.InitializeMatch(2);

      var events = new Queue<TurnEventData>();
      events.Enqueue(CreateTurnEvent(0, playDeck: 10, sidePile: 1, hidden: 0));
      events.Enqueue(CreateTurnEvent(1, playDeck: 9, sidePile: 2, hidden: 1));
      events.Enqueue(CreateTurnEvent(0, playDeck: 7, sidePile: 5, hidden: 3));

      model.UpdatePlayers(events);

      var player0 = model.GetPlayerData(0);
      var player1 = model.GetPlayerData(1);

      Assert.That(player0.PlayDeckCount, Is.EqualTo(7));
      Assert.That(player0.SidePileCount, Is.EqualTo(5));
      Assert.That(player0.HiddenCount, Is.EqualTo(3));

      Assert.That(player1.PlayDeckCount, Is.EqualTo(9));
      Assert.That(player1.SidePileCount, Is.EqualTo(2));
      Assert.That(player1.HiddenCount, Is.EqualTo(1));
    }

    [Test]
    public void IsMatchFinished_ReturnsFalseBeforeResult_AndTrueAfterResult()
    {
      var model = new AppModel();
      model.InitializeMatch(2);

      var beforeFinish = model.IsMatchFinished(out var beforeWinner);
      Assert.That(beforeFinish, Is.False);
      Assert.That(beforeWinner, Is.Null);

      model.UpdateMatchResult(new MatchResultData(1));
      var afterFinish = model.IsMatchFinished(out var afterWinner);

      Assert.That(afterFinish, Is.True);
      Assert.That(afterWinner, Is.EqualTo(1));
    }

    private static TurnEventData CreateTurnEvent(int playerIdx, int playDeck, int sidePile, int hidden)
    {
      return new TurnEventData
      {
        PlayerIdx = playerIdx,
        EventKind = TurnEventKind.RevealTopFromDeck,
        PlayerTurn = new PlayerTurnData
        {
          PlayDeckCount = playDeck,
          SidePileCount = sidePile,
          HiddenCount = hidden,
          RevealedCard = null
        }
      };
    }
  }
}
