using System.Collections.Generic;
using Client.Controller.TurnsProcess;
using NUnit.Framework;
using Shared.SharedModel.Data;

namespace Client.Tests.EditorMode
{
  // Mostly generated by AI
  public class TurnEventsFeedTests
  {
    [Test]
    public void Enqueue_MovesAllEventsAndRaisesOnAddedOnce()
    {
      var feed = new TurnEventsFeed();
      var onAddedCalls = 0;
      feed.OnAdded += () => onAddedCalls++;

      var source = new Queue<TurnEventData>();
      source.Enqueue(CreateTurnEvent(0));
      source.Enqueue(CreateTurnEvent(1));

      feed.Enqueue(source);

      Assert.That(onAddedCalls, Is.EqualTo(1));
      Assert.That(source.Count, Is.EqualTo(0));
      Assert.That(feed.HasEvent, Is.True);

      var first = feed.Dequeue();
      var second = feed.Dequeue();

      Assert.That(first.PlayerIdx, Is.EqualTo(0));
      Assert.That(second.PlayerIdx, Is.EqualTo(1));
      Assert.That(feed.HasEvent, Is.False);
    }

    [Test]
    public void Cleanup_ClearsQueuedEvents()
    {
      var feed = new TurnEventsFeed();
      var source = new Queue<TurnEventData>();
      source.Enqueue(CreateTurnEvent(0));
      source.Enqueue(CreateTurnEvent(1));

      feed.Enqueue(source);
      feed.Cleanup();

      Assert.That(feed.HasEvent, Is.False);
    }

    private static TurnEventData CreateTurnEvent(int playerIdx)
    {
      return new TurnEventData
      {
        PlayerIdx = playerIdx,
        EventKind = TurnEventKind.RevealTopFromDeck,
        PlayerTurn = new PlayerTurnData()
      };
    }
  }
}
