using System;
using System.Collections.Generic;
using Client.Controller.TurnsProcess;
using Client.Model;
using Client.View.MatchEndAnimation;
using Client.View.TurnsAnimation;
using NUnit.Framework;
using Shared.SharedModel.Data;

namespace Client.Tests.EditorMode
{
  // Mostly generated by AI
  public class TurnsProcessorTests
  {
    [Test]
    public void WhenFeedHasMultipleEvents_AnimatesSequentially()
    {
      var turnsAnimator = new FakeTurnsAnimator();
      var matchEndAnimator = new FakeMatchEndAnimator();
      var feed = new TurnEventsFeed();
      var appModel = new AppModel();
      appModel.InitializeMatch(2);

      var processor = new TurnsProcessor(turnsAnimator, feed, matchEndAnimator, appModel);
      processor.Initialize();

      var source = new Queue<TurnEventData>();
      source.Enqueue(CreateTurnEvent(0));
      source.Enqueue(CreateTurnEvent(1));
      feed.Enqueue(source);

      Assert.That(turnsAnimator.AnimateCalls, Is.EqualTo(1));
      Assert.That(turnsAnimator.LastAnimated.PlayerIdx, Is.EqualTo(0));

      turnsAnimator.CompleteLastAnimation();
      Assert.That(turnsAnimator.AnimateCalls, Is.EqualTo(2));
      Assert.That(turnsAnimator.LastAnimated.PlayerIdx, Is.EqualTo(1));

      turnsAnimator.CompleteLastAnimation();
      Assert.That(matchEndAnimator.AnimateCalls, Is.EqualTo(0));

      processor.Dispose();
    }

    [TestCase(0, MatchEndKind.Win)]
    [TestCase(1, MatchEndKind.Lose)]
    [TestCase(null, MatchEndKind.Draw)]
    public void WhenMatchFinishedAndFeedEmpty_AnimatesMatchEnd(int? winnerIdx, MatchEndKind expectedKind)
    {
      var turnsAnimator = new FakeTurnsAnimator();
      var matchEndAnimator = new FakeMatchEndAnimator();
      var feed = new TurnEventsFeed();
      var appModel = new AppModel();
      appModel.InitializeMatch(2);
      appModel.UpdateMatchResult(new MatchResultData(winnerIdx));

      var processor = new TurnsProcessor(turnsAnimator, feed, matchEndAnimator, appModel);
      processor.Initialize();

      Assert.That(matchEndAnimator.AnimateCalls, Is.EqualTo(1));
      Assert.That(matchEndAnimator.LastKind, Is.EqualTo(expectedKind));

      processor.Dispose();
    }

    private static TurnEventData CreateTurnEvent(int playerIdx)
    {
      return new TurnEventData
      {
        PlayerIdx = playerIdx,
        EventKind = TurnEventKind.RevealTopFromDeck,
        PlayerTurn = new PlayerTurnData()
      };
    }

    private class FakeTurnsAnimator : ITurnsAnimator
    {
      private Action _lastOnFinished;

      public int AnimateCalls { get; private set; }
      public TurnEventData LastAnimated { get; private set; }

      public void Animate(TurnEventData turnData, Action onAnimationFinished)
      {
        AnimateCalls++;
        LastAnimated = turnData;
        _lastOnFinished = onAnimationFinished;
      }

      public void CompleteLastAnimation()
      {
        var callback = _lastOnFinished;
        _lastOnFinished = null;
        callback?.Invoke();
      }
    }

    private class FakeMatchEndAnimator : IMatchEndAnimator
    {
      public int AnimateCalls { get; private set; }
      public MatchEndKind? LastKind { get; private set; }

      public void Animate(MatchEndKind kind)
      {
        AnimateCalls++;
        LastKind = kind;
      }
    }
  }
}
