using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace Client.View.UiControl
{
  // Class mostly generated by AI
  public class MultiTargetButton : Button
  {
    [SerializeField] private List<Graphic> _extraTargets = new();

    protected override void DoStateTransition(SelectionState state, bool instant)
    {
      base.DoStateTransition(state, instant);

      var tint = state switch
      {
        SelectionState.Normal => colors.normalColor,
        SelectionState.Highlighted => colors.highlightedColor,
        SelectionState.Pressed => colors.pressedColor,
        SelectionState.Selected => colors.selectedColor,
        SelectionState.Disabled => colors.disabledColor,
        _ => Color.white
      };

      var duration = instant 
        ? 0f 
        : colors.fadeDuration;
      
      foreach (var g in _extraTargets)
      {
        if (g == null) 
          continue;
        
        g.CrossFadeColor(tint * colors.colorMultiplier, duration, true, true);
      }
    }
  }
}